module.exports = {
  projects: [
    '<rootDir>/libs/client/domain',
    '<rootDir>/apps/client',
    '<rootDir>/libs/client/feature-account',
    '<rootDir>/libs/client/ui-message',
    '<rootDir>/libs/client/util-message',
    '<rootDir>/libs/client/util-peers',
    '<rootDir>/libs/client/feature-message',
    '<rootDir>/libs/client/shell',
    '<rootDir>/libs/client/feature-meeting',
    '<rootDir>/libs/client/util-peer',
    '<rootDir>/apps/server',
    '<rootDir>/libs/core/entities',
    '<rootDir>/libs/core/config',
    '<rootDir>/libs/common/ui-material',
    '<rootDir>/libs/client/feature-workshop',
    '<rootDir>/libs/client/ui-media',
  ],
}
